#!/bin/sh -e
#
### BEGIN INIT INFO
# Provides:          kibana-templates-load-in-es
# Required-Start:    $elasticsearch $nginx $time $network $local_fs $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Loads Kibana templates in ES from cmd
# Description:       Loads Kibana templates in ES from cmd
#                    which is different from the way loading 
#                    of templates works through the regular GUI
### END INIT INFO

## System boot time configuration script
## Stamus Networks
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.

case "$1" in
  start)
    
    # check if port 9200 is open/listening
    # sometimes afetr starting ES it takes 10-15 sec to 
    # get 9200 to open and accept connections
    # otherwise we fail
    counter=0
    while ! echo exit | nc localhost 9200; do 
      counter=$((counter + 1))
      echo  "Port 9200 is NOT listening/open !!";
      echo  "The script will retry to connect 6 times - once every 10 sec"; 
      echo  "and exit afterwords if not successful!"; echo;
      if [ "$counter" -lt 6 ]; then
        sleep 10 
      else
        echo "Tried to connect 6 times already...exiting!"
        exit 1
      fi
    done
    
    cd /opt/selks/KibanaTemplatesCmdLoad/ && \
    for i in $( dir -1 ); do  curl -v -X PUT http://localhost:9200/kibana-int/dashboard/${i} -T ${i} ; done
  ;;
  stop|status|restart|reload|force-reload)
    # do nothing
  ;;
esac
